"""Add License model in cdn subapp

Revision ID: 472a138bca2c
Revises: 7a08fb63ca62
Create Date: 2024-11-12 04:36:31.698999

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '472a138bca2c'
down_revision = '7a08fb63ca62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
