"""Add content model

Revision ID: 7a08fb63ca62
Revises: 1a31ce608336
Create Date: 2024-11-06 07:10:10.008554

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes

import app

# revision identifiers, used by Alembic.
revision = '7a08fb63ca62'
down_revision = '1a31ce608336'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contentitem',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('url', app.models.HttpUrlType(length=2083), nullable=False),
    sa.Column('hash', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contentitem_url'), 'contentitem', ['url'], unique=True)
    op.create_table('contentlicenseitem',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('url', app.models.HttpUrlType(length=2083), nullable=False),
    sa.Column('hash', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contentlicenseitem_url'), 'contentlicenseitem', ['url'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contentlicenseitem_url'), table_name='contentlicenseitem')
    op.drop_table('contentlicenseitem')
    op.drop_index(op.f('ix_contentitem_url'), table_name='contentitem')
    op.drop_table('contentitem')
    # ### end Alembic commands ###
